release-schema.json, README.md: add to lot object
open-contracting-extensions/ocds_essentialAssets_extension pull request #2
Opened 2023-04-05 12:35 UTC by odscjen

2023-04-10 22:46 UTC, duncandewhurst requested changes

2023-04-10 22:46 UTC, duncandewhurst commented on README.md
> +Adds a object to the tender and lot objects to describe the assets used for the provision of public services.
```suggestion
Adds an object to the tender and lot objects to describe the assets used for the provision of public services.
```

2023-04-10 22:46 UTC, duncandewhurst commented on README.md
> +In the European Union, this extension's fields correspond to [eForms OPT-020-Contract (Assets related contract extension indicator), OPT-021-Contract (Used asset), OPT-022-Contract (Significance (%))
Any reason not to leave the reference to the EU regulation (in addition to the eForms business terms?

2023-04-13 03:57 UTC, duncandewhurst approved these changes

2023-04-13 20:57 UTC, jpmckinney commented on README.md
> +In the European Union, this extension's fields correspond to [Article 4, clause 4 of Regulation 1370/2007](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32007R1370) and [eForms OPP-020-
In other reviews, Duncan had written:

> As in the other PRs, I think that we should preserve the reference to OCDS for the European Union.

```suggestion
In the European Union, this extension's fields correspond to [Article 4, clause 4 of Regulation 1370/2007](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32007R1370) and [eForms OPP-020-Contract (Assets related contract extension indicator), OPP-021-Contract (Used asset), OPP-022-Contract (Significance (%)), and OPP-023-Contract (Predominance (%))](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). See [OCDS for eForms](https://standard.open-contracting.org/profiles/eforms/latest/en/) for the correspondences to eForms fields. See [OCDS for the European Union](http://standard.open-contracting.org/profiles/eu/master/en/) for the correspondences to Tenders Electronic Daily (TED).
```

2023-04-13 20:57 UTC, jpmckinney commented on release-schema.json
>              "string",
Note: Significance and Predominance are `string` for OCDS for EU, because the TED schema is very lax (it allows paragraph descriptions here). It looks like eForms is also lax, as the type is text with a maxLength of 30, where it could have used a narrower type.

2023-04-18 10:53 UTC, odscjen commented on release-schema.json
>              "string",
ah, good to know

2023-04-18 15:40 UTC, jpmckinney approved these changes

2023-04-18 15:40 UTC, merged